apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: quiz-service
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.quiz.apiPort }}