---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cost-{{ .Release.Namespace }}
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cost-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.cost.serviceAccountName }}
roleRef:
  kind: ClusterRole
  name: cost-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: costsvc
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["hobbyfarm.io"]
    resources: ["costs"]
    verbs: ["*"]
  {{- if .Values.cost.trackableResources }}
  {{- range .Values.cost.trackableResources }}
  - apiGroups: ["{{ .group }}"]
    resources: ["{{ .resource }}"]
    verbs: ["list", "watch"]
  {{- end }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: costsvc
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.cost.serviceAccountName }}
roleRef:
  kind: Role
  name: costsvc
  apiGroup: rbac.authorization.k8s.io
