apiVersion: v1
kind: Service
metadata:
  name: cost-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: cost-service
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.cost.apiPort }}